### ISSUE TITLE
Error since updating to docpad v6.78.1

### ISSUE THREAD

**Issue by williammalo** [pflannery/docpad-plugin-traceur#3]
I tried reinstalling node, reinstalling traceur, etc. etc. nothing works
I get this error:

    TypeError: Cannot read property 'compileFile' of undefined

when I require traceur in node, I get this:

    { recursiveModuleCompileToSingleFile: [Function: recursiveModuleCompileToSingleFile],
    forEachRecursiveModuleCompile: [Function: forEachRecursiveModuleCompile],
    compileAllJsFilesInDir: [Function: compileAllJsFilesInDir],
    NodeCompiler: [Function: NodeCompiler],
    compile: [Function: compile],
    commonJSOptions: [Function],
    amdOptions: [Function],
    closureOptions: [Function],
    RUNTIME_PATH: '/Users/will/Dropbox/clients/web.signshop/node_modules/traceur/bin/traceur-runtime.js' }

did node traceur change it's api?

**Comment by pflannery** [comment]
Yeah the API had changed. I've updated and published as v2.2.0 on npm ;)
Let me know how it goes thanks.

**Comment by williammalo** [comment]
ah thanks! I really need this plugin for my work.

**Comment by pflannery** [comment]
:+1:  closing
